stages:
  - analysis
  - build
  - test-build
  - deploy

workflow:
  rules:
    - when: always

variables:
  GIT_DEPTH: 1

.tags_manylinux_2_28:
  tags: ["manylinux_2_28"]

.tags_win10:
  tags: ["eo", "win10", "arepytools-win"]

.tags_deploy:
  tags: ["eo", "deploy"]

default:
  before_script:
    - cd $SUBPROJECT

# === analysis ===============================================================
# ============================================================================
check_code_compliance_ruff:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s check_format

check_code_compliance_pylint:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s pylint

version_check:
  stage: analysis
  extends:
    - .tags_manylinux_2_28
  script:
    - python3 -m pip install nox
    - python3 -m nox -s version_consistency_check

# === build ==================================================================
# ============================================================================
sdist:
  stage: build
  extends:
    - .tags_manylinux_2_28
  script:
    - python3.12 -m pip install nox
    - python3.12 -m nox -s build_sdist
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.tar.gz

python_package_linux:
  stage: build
  script:
    - python${PYTHON} -m pip install nox
    - python${PYTHON} -m nox -s build_python_package -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  extends: .tags_manylinux_2_28
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.whl

python_package_win:
  stage: build
  script:
    - $env:CC = 'gcc'
    - $env:CXX = 'gcc'
    - python -m pip install nox
    - python -m nox -s build_python_package -p ${PYTHON}
  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  extends: .tags_win10
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.whl

# === test wheel =============================================================
# ============================================================================
test_wheel_linux:
  stage: test-build
  script:
    - export match="cp${PYTHON/./}"
    - python${PYTHON} -m venv ./ci_test
    - source ./ci_test/bin/activate
    - python -m pip install --find-links= dist/*$match*.whl
    - cd ..
    - python -m pip install pytest pytest-cov
    - >
      python -m pytest ${SUBPROJECT}/tests/
      --junitxml=_build/pytest-report-linux-py${PYTHON}.xml
      --cov-report=xml:_build/pytest-coverage-linux-py${PYTHON}.xml
  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  extends: .tags_manylinux_2_28
  needs:
    - job: python_package_linux
  artifacts:
    reports:
      junit:
        - ./_build/pytest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: ./_build/pytest-coverage-*.xml

test_wheel_win10:
  stage: test-build
  script:
    - $match = "cp${PYTHON}".replace(".", "")
    - $wheel_py = Get-ChildItem -Path dist -Filter *$match*.whl -Recurse | ForEach-Object{$_.FullName}
    - cd ..
    - pyenv local ${PYTHON}
    - python -m pip install $wheel_py
    - python -m pip install pytest pytest-cov
    - >
      python -m pytest ${SUBPROJECT}/tests/
      --junitxml=_build/pytest-report-win-py${PYTHON}.xml
      --cov-report=xml:_build/pytest-coverage-win-py${PYTHON}.xml
  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  extends: .tags_win10
  needs:
    - job: python_package_win
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit:
        - ./_build/pytest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: ./_build/pytest-coverage-*.xml

# === deploy =================================================================
# ============================================================================
deploy_package:
  stage: deploy
  extends: .tags_deploy
  rules:
    - if: "$CI_COMMIT_TAG"
  script:
    - eval "$(ssh-agent -s)"
    - cd ..
    - for file in ${SUBPROJECT}/dist/*.tar.gz ${SUBPROJECT}/dist/*.whl; do
      eo_pgp-signme ${file} > ${file}.asc &&
      ./.gitlab/ci/dashboard-copy.sh ${file} develop/perseo/perturbations/archive &&
      ./.gitlab/ci/dashboard-copy.sh ${file}.asc develop/perseo/perturbations/archive;
      done
