stages:
  - analysis
  - test
  - build

workflow:
  rules:
    - when: always

variables:
  GIT_DEPTH: 1

.tags_manylinux_2_28:
  tags: ["eotools_manylinux228"]

.tags_manylinux_2_28_std:
  tags: ["manylinux_2_28"]

.tags_win10_new:
  tags: ["eotools_win10"]

.tags_win10:
  tags: ["eo", "win10", "arepytools-win"]

default:
  before_script:
    - cd $SUBPROJECT

# === analysis ===============================================================
# ============================================================================
check_code_compliance_ruff:
  stage: analysis
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install ruff
    - python3.12 -m ruff --version
    - python3.12 -m ruff format --check .
    - python3.12 -m ruff check .

check_code_compliance_pylint:
  stage: analysis
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install pylint
    - python3.12 -m pylint --version
    - python3.12 -m pylint ./src/perseo_quality

# === test - unittest ========================================================
# ============================================================================
unittest_linux:
  stage: test
  extends: .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install -e .[dev,test,graphs]
    - mkdir -p _build
    - python -m pytest ./tests/ \
      --junitxml=_build/pytest-report-linux-py${PYTHON}.xml \
      --cov-report=xml:_build/pytest-coverage-linux-py${PYTHON}.xml

  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit:
        - ${SUBPROJECT}/_build/pytest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: ${SUBPROJECT}/_build/pytest-coverage-*.xml

unittest_win:
  stage: test
  extends: .tags_win10
  script:
    - python -m pip install -e .[dev,test,graphs]
    - if (-not (Test-Path _build)) { New-Item -ItemType Directory -Path _build | Out-Null }
      python -m pytest ./tests/ --junitxml=_build/pytest-report-win-py${PYTHON}.xml --cov-report=xml:_build/pytest-coverage-win-py${PYTHON}.xml

  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  needs: []
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit:
        - ${SUBPROJECT}/_build/pytest-report-*.xml
      coverage_report:
        coverage_format: cobertura
        path: ${SUBPROJECT}/_build/pytest-coverage-*.xml

# === test - integration =====================================================
# ============================================================================
integration_test_linux:
  stage: test
  script:
    - python${PYTHON} -m venv ./ci_test
    - source ./ci_test/bin/activate
    - python -m pip install .[graphs]
    - pip install sct[cli,graphs]
    - python -m pip install sct_aresys_reader sct_sentinel1_reader
    - sct testing test -r ./tests/integration_tests/test_registry_linux.json -out ./test_output
  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13", "3.14"]
  extends: .tags_manylinux_2_28
  needs: []

integration_test_windows:
  stage: test
  script:
    - . "C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\profile.ps1"
    - conda create -y -n integration_test python=${PYTHON}
    - conda activate integration_test
    - python -m pip install -e .[graphs]
    - pip install sct[cli,graphs]
    - python -m pip install sct_aresys_reader sct_sentinel1_reader
    - sct testing test -r ./tests/integration_tests/test_registry_windows.json -out ./test_output
  parallel:
    matrix:
      - PYTHON: ["3.11", "3.12", "3.13"]
  extends: .tags_win10_new
  needs: []

# === build ==================================================================
# ============================================================================
package:
  stage: build
  extends:
    - .tags_manylinux_2_28_std
  script:
    - python3.12 -m pip install build
    - python3.12 -m build
  needs: []
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${SUBPROJECT}/dist/*.tar.gz
      - ${SUBPROJECT}/dist/*.whl
